[package]
name = "threading"
version = "0.1.0"
authors = ["mdrokz <mohammadmunshi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="rust_threading"
crate-type = ["cdylib"]


[dependencies]
hlua = "0.4.1"
